### ISSUE TITLE
terminal window is opened with anacona one, viperr 7 beta 2

### ISSUE THREAD

**Issue by FredBezies** [azgaviperr/Viperr#12]
When anaconda is launched, a terminal is also opened. See screenshot :

![001](https://cloud.githubusercontent.com/assets/8571419/8453096/696ed686-1ff1-11e5-929a-b8cffca151b9.png)

**Comment by penthium2** [comment]
It's normal ! it's the way to launch anaconda in root mode

**Comment by FredBezies** [comment]
Ok. It is just annonying. Sorry for reporting this "not really" bug :(
