### ISSUE TITLE
Installer window is not correctly named.

### ISSUE THREAD

**Issue by FredBezies** [azgaviperr/Viperr#13]
A simple bug to see. Just launch viperr 7 beta 2 and wait for installer to be launched. Installer windows is known as "unnamed window".

A screenshot of this bug can be seen in this issue : https://github.com/azgaviperr/Viperr/issues/12

**Comment by penthium2** [comment]
Not a issue for me.

**Comment by FredBezies** [comment]
Ok. It was just annoying. Sorry !
