### ISSUE TITLE
Openbox main menu is not correctly modified after adding LibreOffice to Viperr

### ISSUE THREAD

**Issue by FredBezies** [azgaviperr/Viperr#14]
A strange bug very simple to reproduce. When you install LibreOffice using post-install script, it is not added to openbox main menu.

Only "traitement de texte" is listed but not a link for LibreOffice. It is installed, as you can run it from command line using soffice &.

See screenshot. LibreOffice is launched, but not listed in openbox menu. Weird !

![002](https://cloud.githubusercontent.com/assets/8571419/8453745/0638133c-1ff8-11e5-9ad1-3d3786de9350.png)

**Comment by FredBezies** [comment]
Looks like it is a bug in script.

If you answer yes to Libreoffice, lo="libreoffice libreoffice-langpack-fr"

And later, when menu must be modified,you can see : 

if [ "$lo" =  "libreoffice" ]

I'm not that good in bash script, but it won't match as $lo is something different.

**Comment by penthium2** [comment]
Yes it is ! 
Thank a lot :dancer: 
update of viperrconf should solved this issue for futur user.

**Comment by FredBezies** [comment]
Still not fixed as of viperr 7 beta 4... Still facing it. Bad ISO mastering ?

**Comment by penthium2** [comment]
fixed in viperrconf-7.21-viperr.fc22.noarch.rpm
update of viperrconf should solved this issue for futur user.

**Comment by azgaviperr** [comment]
Evertything fine in the final version
