### ISSUE TITLE
"langpacks : no language are enabled" in post-install script.

### ISSUE THREAD

**Issue by FredBezies** [azgaviperr/Viperr#15]
While processing post install script in viperr 7 beta 4, "langpacks : no language are enabled" appears at least 3 or 4 times.

A bash script bug ?

**Comment by azgaviperr** [comment]
Official bug for dnf here >>  https://bugzilla.redhat.com/show_bug.cgi?id=1244531
No arm is done by this but can be annoying.
Not a "Viperr" issue so I close the ticket
