### ISSUE TITLE
Composite rendering cannot be launched in Viperr 7 beta 4

### ISSUE THREAD

**Issue by FredBezies** [azgaviperr/Viperr#16]
You cannot launch composite rendering.

Just try to launch it, you'll get a warning box telling you script cannot be found. Ouch !

See screenshot.
![002](https://cloud.githubusercontent.com/assets/8571419/8846170/18373bc4-3125-11e5-81f4-62399baa0de1.png)

**Comment by penthium2** [comment]
fixed in viperrconf-7.21-viperr.fc22.noarch.rpm
update of viperrconf should solved this issue for futur user.

**Comment by azgaviperr** [comment]
Je confirme que la version finale ne dispose pas de cette incohérence
