### ISSUE TITLE
System Bootup - Enters emergency mode after update to kernel 3.19.7

### ISSUE THREAD

**Issue by ramaseshan** [azgaviperr/Viperr#6]
Recently did an update, and the system started to enter emergency mode on every boot.

Here is the sample log :
Generation /run/initramfs/rdsosreport.txt 

Entering emergency Mode. Exit the shell to continue
Enter "journalctl" to view system logs.
You might want to save /run/initramfs/rdsosreport.txt to a USB stick or /boot

Welcome to emergency mode. After logging in type "journalctl -xb " to view system logs after executing that attach that to the bug report.

Enter root password for maintaince:
(Press ctrl+D to continue)

Without pressing ctrl + D, it just doesnt boot up.

Attached the files for reference.
https://gist.github.com/ramaseshan/28bfc76c78a560c7fa51

https://gist.github.com/ramaseshan/ec55a8f05c74f931894c

Let me know if you need anymore info

**Comment by penthium2** [comment]
Jun 04 19:41:50 localhost.localdomain kernel: EXT4-fs error (device sda2): ext4_mb_generate_buddy:757: group 82, block bitmap and bg descriptor inconsistent: 27728 vs 27732 free clusters
Jun 04 19:41:50 localhost.localdomain kernel: EXT4-fs error (device sda2): ext4_mb_generate_buddy:757: group 83, block bitmap and bg descriptor inconsistent: 26382 vs 26375 free clusters
Jun 04 19:41:51 localhost.localdomain kernel: JBD2: Spotted dirty metadata buffer (dev = sda2, blocknr = 0). There's a risk of filesystem corruption in case of system crash.

You have a risk of filesystem corruption, so you enter in emergengy mode.

**Comment by penthium2** [comment]
Jun 04 19:33:53 localhost.localdomain kernel: EXT4-fs error (device sda2): ext4_mb_generate_buddy:757: group 129, block bitmap and bg descriptor inconsistent: 23234 vs 23235 free clusters

Hum ! may be it's why you go to emergency ! check your disk.
