### ISSUE TITLE
Quit menu doesn't work : obsession-logout core dumps.

### ISSUE THREAD

**Issue by FredBezies** [azgaviperr/Viperr#9]
Simple to see and reproduce.

Download beta1, copy it on a USB key, boot a computer.

After installer is loaded, closed it. Go to menu / quit. Nothing happens.

Got this error message in /var/log/message : 

`Jun 27 07:50:56 localhost dbus[621]: [system] Rejected send message, 2 matched rules; type="method_call", sender=":1.32" (uid=1000 pid=7342 comm="/usr/bin/obsession-logout ") interface="org.freedesktop.DBus.Properties" member="GetAll" error name="(unset)" requested_reply="0" destination=":1.33" (uid=0 pid=7344 comm="/usr/sbin/console-kit-daemon --no-daemon ")`
`Jun 27 07:50:57 localhost kernel: do_trap: 30 callbacks suppressed`
`Jun 27 07:50:57 localhost kernel: traps: obsession-logou[7342] trap invalid opcode ip:402b26 sp:7ffea4535f20 error:0 in obsession-logout[400000+6000]`
`Jun 27 07:50:57 localhost audit: <audit-1701> auid=1000 uid=1000 gid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=7342 comm="obsession-logou" exe="/usr/bin/obsession-logout" sig=4﻿`

And with SELinux disabled : 

`Jun 27 09:26:31 localhost audit: <audit-1701> auid=1000 uid=0 gid=0 ses=1 pid=1830 comm="obsession-logou" exe="/usr/bin/obsession-logout" sig=4`
`Jun 27 09:26:31 localhost kernel: traps: obsession-logou[1830] trap invalid opcode ip:402b26 sp:7fffa086f9b0 error:0 in obsession-logout[400000+6000]`

**Comment by azgaviperr** [comment]
It's possible to fix it by modification of the command in the openbox menu.
actual is "/usr/bin/obsession-logout" it should be "/usr/bin/obsession-exit -s"
So the exit function is working properly. But badly set in the menu. However the logout option of obsession  is buggy.

**Comment by azgaviperr** [comment]
Pour information, on va peut être passé par un script python pour l'extinction.
Le rpm n'est pas encore installable avec dnf ou yumex mais disponible ici.

http://coyotus.com/viperr/repo/Viperr/7/base/vp-exit-0.0.1-2.viperr.fc22.noarch.rpm

**Comment by FredBezies** [comment]
Je viens de tester, l'ensemble est vraiment très agréable et sympathique à l'utilisation. Merci pour l'information !

**Comment by azgaviperr** [comment]
Fixed in the final version and tested on the lastest Beta.
